
DROP TABLE ATTACHMENT;
DROP TABLE USERS;
DROP TABLE QUESTION;

DROP SEQUENCE SEQ_USERNO; -- <유저>테이블 - 유저번호

--------------------------------------------------------------------------------
--###############  첨부파일  ###############
--------------------------------------------------------------------------------
CREATE TABLE ATTACHMENT(
    FILE_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(255) NOT NULL,
    CHANGE_NAME VARCHAR2(255) NOT NULL UNIQUE,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL CHECK(STATUS IN ('Y', 'N')) -- 미삭제:Y/삭제:N
);

COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태';

-- 주의! <첨부파일> 테이블이 <유저>테이블 보다 위에서 선언되야함. 이렇게 안하면 에러남.
-- 이유: <유저>테이블에서 <첨부파일> 테이블을 외래키로 사용하고 있음.

--------------------------------------------------------------------------------
--###############  유저  ###############
--------------------------------------------------------------------------------
CREATE TABLE USERS( -- USER는 예약어라 사용불가. USERS로 변경함.
    -- (참고) 제약조건명을 넣었더니 너무 복잡해보임... 이미 해둔건 남겨두고, 다른 테이블에는 적용 안하는게 나을듯?
    USER_NO NUMBER CONSTRAINT USERNO_PK PRIMARY KEY,
    USER_ID VARCHAR2(20) CONSTRAINT USERID_NN NOT NULL,
    USER_PWD VARCHAR2(20) CONSTRAINT USERPWD_NN NOT NULL,
    USER_NAME VARCHAR2(20) CONSTRAINT USERNAME_NN NOT NULL,
    PHONE VARCHAR2(13) CONSTRAINT PHONE_NN NOT NULL,
    BIRTHDAY DATE CONSTRAINT BIRTHDAY_NN NOT NULL,
    EMAIL VARCHAR2(30),
    ADDRESS VARCHAR2(100),
    ENROLL_DATE DATE DEFAULT SYSDATE CONSTRAINT ENROLLDATE_NN NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE CONSTRAINT MODIFYDATE_NN NOT NULL,
    PROFILE_FILE_NO NUMBER CONSTRAINT PROFILEFILENO_FK REFERENCES ATTACHMENT,
    QUESTION_NO NUMBER CONSTRAINT QUESTIONNO_NN NOT NULL,
    QUESTION_ANSWER VARCHAR2(50) CONSTRAINT QUESTIONANSWER_NN NOT NULL, 
    USER_AUTH CHAR(1) DEFAULT 'U' CONSTRAINT USERAUTH_NN NOT NULL, -- 일반유저:U/관리자:A
    STATUS CHAR(1) DEFAULT 'Y' CONSTRAINT STATUS_NN NOT NULL, -- 미탈퇴:Y/탈퇴:N
    GITHUB_URL VARCHAR2(100),
    NOTION_URL VARCHAR2(100),
    CONSTRAINT USERID_UQ UNIQUE(USER_ID),
    CONSTRAINT PHONE_UQ UNIQUE(PHONE),
    CONSTRAINT USERAUTH_CK CHECK(USER_AUTH IN ('U', 'A')),
    CONSTRAINT STATUS_CK CHECK(STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN USERS.USER_NO IS '유저번호'; 
COMMENT ON COLUMN USERS.USER_ID IS '유저아이디'; 
COMMENT ON COLUMN USERS.USER_PWD IS '유저비밀번호';
COMMENT ON COLUMN USERS.USER_NAME IS '유저이름'; 
COMMENT ON COLUMN USERS.PHONE IS '전화번호'; 
COMMENT ON COLUMN USERS.BIRTHDAY IS '생일';
COMMENT ON COLUMN USERS.EMAIL IS '이메일'; 
COMMENT ON COLUMN USERS.ADDRESS IS '주소'; 
COMMENT ON COLUMN USERS.ENROLL_DATE IS '회원가입일'; 
COMMENT ON COLUMN USERS.MODIFY_DATE IS '정보수정일'; 
COMMENT ON COLUMN USERS.PROFILE_FILE_NO IS '프로필사진';
COMMENT ON COLUMN USERS.QUESTION_NO IS '질문번호'; 
COMMENT ON COLUMN USERS.QUESTION_ANSWER IS '질문답변'; 
COMMENT ON COLUMN USERS.USER_AUTH IS '유저권한';
COMMENT ON COLUMN USERS.STATUS IS '상태';
COMMENT ON COLUMN USERS.GITHUB_URL IS '깃허브주소';
COMMENT ON COLUMN USERS.NOTION_URL IS '노션주소';

CREATE SEQUENCE SEQ_USERNO
NOCACHE;



--------------------------------------------------------------------------------
--###############  질문  ############### 아이디/비밀번호 찾기용
--------------------------------------------------------------------------------
CREATE TABLE QUESTION(
    QUESTION_NO NUMBER PRIMARY KEY,
    QUESTION_CONTENT VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN QUESTION.QUESTION_NO IS '질문번호';
COMMENT ON COLUMN QUESTION.QUESTION_CONTENT IS '질문내용';
