
--------------------------------------------------------------------------------
--############### 기존 데이터 삭제  ###############
--------------------------------------------------------------------------------
-- CASCADE CONSTRAINTS를 해줘야 외래키로 엮어있는 데이터들이 잘 지워짐.
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE COMMENT_REPLY CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE CONTACTS_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE CONTACTS CASCADE CONSTRAINTS;
DROP TABLE CONTACTS_MEMBER CASCADE CONSTRAINTS;
DROP TABLE CONTACTS_STAR CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_FILENO;                  -- <첨부파일> 테이블 PK시퀀스
DROP SEQUENCE SEQ_USERNO;                 -- <유저> 테이블 PK시퀀스
DROP SEQUENCE SEQ_QUESTIONNO;          -- <질문> 테이블 PK시퀀스
DROP SEQUENCE SEQ_COMMENTNO;         -- <댓글> 테이블 PK시퀀스
DROP SEQUENCE SEQ_COMREPLYNO;         -- <댓글_답글> 테이블 PK시퀀스
DROP SEQUENCE SEQ_NOTINO;                 -- <알림> 테이블 PK시퀀스
DROP SEQUENCE SEQ_CONTACTS_CATENO;  -- <주소록_카테고리> 테이블 PK시퀀스
DROP SEQUENCE SEQ_CONTACTSNO;          -- <주소록> 테이블 PK시퀀스
DROP SEQUENCE SEQ_CONTACTS_STARNO;  -- <주소록_중요표시> 테이블 PK시퀀스

-- 주의! <첨부파일>, <QUESTION> 테이블이 <USERS>테이블 보다 위에서 선언되야함. 이렇게 안하면 에러남.
-- 이유: <USERS>테이블에서 <ATTACHMENT>, <QUESTION> 테이블을 외래키로 사용하고 있는데,
--        다른 두 테이블이 생성되지 않은 상태에서 <USERS>테이블이 먼저 읽히면, 해당 테이블들을 인식못하게됨. 결국 에러로 <USERS>테이블이 생성안되게됨.

--------------------------------------------------------------------------------
--###############  첨부파일  ###############
--------------------------------------------------------------------------------
CREATE TABLE ATTACHMENT(
    FILE_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(255) NOT NULL,
    CHANGE_NAME VARCHAR2(255) NOT NULL UNIQUE,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL CHECK(STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태(미삭제:Y/삭제:N)';

CREATE SEQUENCE SEQ_FILENO
NOCACHE;

INSERT INTO ATTACHMENT VALUES(SEQ_FILENO.NEXTVAL, 'apple.jpg', 'apple1.jpg', '/SiyeonSchool/upfiles/', SYSDATE, DEFAULT);
INSERT INTO ATTACHMENT VALUES(SEQ_FILENO.NEXTVAL, 'apple.jpg', 'apple2.jpg', '/SiyeonSchool/upfiles/', SYSDATE, DEFAULT);
INSERT INTO ATTACHMENT VALUES(SEQ_FILENO.NEXTVAL, 'apple.jpg', 'apple3.jpg', '/SiyeonSchool/upfiles/', SYSDATE, DEFAULT);
INSERT INTO ATTACHMENT VALUES(SEQ_FILENO.NEXTVAL, 'apple.jpg', 'apple4.jpg', '/SiyeonSchool/upfiles/', SYSDATE, DEFAULT);
INSERT INTO ATTACHMENT VALUES(SEQ_FILENO.NEXTVAL, 'apple.jpg', 'apple5.jpg', '/SiyeonSchool/upfiles/', SYSDATE, DEFAULT);

--------------------------------------------------------------------------------
--###############  질문  ############### (아이디/비밀번호 찾기용)
--------------------------------------------------------------------------------
CREATE TABLE QUESTION(
    QUESTION_NO NUMBER PRIMARY KEY,
    QUESTION_CONTENT VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN QUESTION.QUESTION_NO IS '질문번호';
COMMENT ON COLUMN QUESTION.QUESTION_CONTENT IS '질문내용';

CREATE SEQUENCE SEQ_QUESTIONNO
NOCACHE;

INSERT INTO QUESTION VALUES(SEQ_QUESTIONNO.NEXTVAL, '기억에 남는 추억의 장소는?');
INSERT INTO QUESTION VALUES(SEQ_QUESTIONNO.NEXTVAL, '자신의 인생 좌우명은?');
INSERT INTO QUESTION VALUES(SEQ_QUESTIONNO.NEXTVAL, '자신의 보물 제1호는?');
INSERT INTO QUESTION VALUES(SEQ_QUESTIONNO.NEXTVAL, '가장 기억에 남는 선생님 성함은?');
INSERT INTO QUESTION VALUES(SEQ_QUESTIONNO.NEXTVAL, '추억하고 싶은 날짜가 있다면?');

--------------------------------------------------------------------------------
--###############  유저  ###############
--------------------------------------------------------------------------------
CREATE TABLE USERS( -- USER는 예약어라 테이블명에 사용 못함. 대신 뒤에 S를 붙여 사용.
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(20) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(13) NOT NULL UNIQUE,
    BIRTHDAY DATE NOT NULL,
    EMAIL VARCHAR2(30),
    ADDRESS VARCHAR2(100),
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
    PROFILE_FILE_NO NUMBER,
    QUESTION_NO NUMBER NOT NULL,
    QUESTION_ANSWER VARCHAR2(50)  NOT NULL, 
    USER_AUTH CHAR(1) DEFAULT 'U' NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    GITHUB_URL VARCHAR2(100),
    NOTION_URL VARCHAR2(100),
    FOREIGN KEY (PROFILE_FILE_NO) REFERENCES ATTACHMENT(FILE_NO),
    FOREIGN KEY (QUESTION_NO) REFERENCES QUESTION(QUESTION_NO),
    CHECK(USER_AUTH IN ('U', 'A')),
    CHECK(STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN USERS.USER_NO IS '유저번호'; 
COMMENT ON COLUMN USERS.USER_ID IS '유저아이디'; 
COMMENT ON COLUMN USERS.USER_PWD IS '유저비밀번호';
COMMENT ON COLUMN USERS.USER_NAME IS '유저이름'; 
COMMENT ON COLUMN USERS.PHONE IS '전화번호'; 
COMMENT ON COLUMN USERS.BIRTHDAY IS '생일';
COMMENT ON COLUMN USERS.EMAIL IS '이메일'; 
COMMENT ON COLUMN USERS.ADDRESS IS '주소'; 
COMMENT ON COLUMN USERS.ENROLL_DATE IS '회원가입일'; 
COMMENT ON COLUMN USERS.MODIFY_DATE IS '정보수정일'; 
COMMENT ON COLUMN USERS.PROFILE_FILE_NO IS '프로필사진';
COMMENT ON COLUMN USERS.QUESTION_NO IS '질문번호'; 
COMMENT ON COLUMN USERS.QUESTION_ANSWER IS '질문답변'; 
COMMENT ON COLUMN USERS.USER_AUTH IS '유저권한(일반유저:U/관리자:A)';
COMMENT ON COLUMN USERS.STATUS IS '상태(미탈퇴:Y/탈퇴:N)';
COMMENT ON COLUMN USERS.GITHUB_URL IS '깃허브주소';
COMMENT ON COLUMN USERS.NOTION_URL IS '노션주소';

CREATE SEQUENCE SEQ_USERNO
NOCACHE;

INSERT INTO USERS VALUES (SEQ_USERNO.NEXTVAL, 'admin', '1234', '나관리', '010-1111-2222', TO_DATE(19950101), 'admin@kh.or.kr', '서울시 강남구 역삼동', SYSDATE, SYSDATE, NULL, 1, '방과후 옥상', 'A', DEFAULT, NULL, NULL);
INSERT INTO USERS VALUES (SEQ_USERNO.NEXTVAL, 'user01', 'pass01', '차은우', '010-3333-4444', TO_DATE(19980820), 'user01@kh.or.kr', '서울시 양천구 목동', SYSDATE, SYSDATE, NULL, 2, '내가제일잘나가', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO USERS VALUES (SEQ_USERNO.NEXTVAL, 'user02', 'pass02', '주지훈', '010-5555-6666', TO_DATE(19941123), 'user02@kh.or.kr', '서울시 강서구', SYSDATE, SYSDATE, NULL, 3, '내얼굴', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO USERS VALUES (SEQ_USERNO.NEXTVAL, 'user03', 'pass03', '장원영', '010-7777-8888', TO_DATE(20000227), 'user03@kh.or.kr', '인천', SYSDATE, SYSDATE, NULL, 4, '우리의그분', DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO USERS VALUES (SEQ_USERNO.NEXTVAL, 'user04', 'pass04', '손흥민', '010-7777-7777', TO_DATE(19920603), 'user04@kh.or.kr', '경기도', SYSDATE, SYSDATE, NULL, 5, '2022-02-22', DEFAULT, DEFAULT, NULL, NULL);

--------------------------------------------------------------------------------
--###############  댓글  ###############
--------------------------------------------------------------------------------
CREATE TABLE COMMENTS( -- COMMENT는 예약어라 테이블명에 사용 못함. 대신 뒤에 S를 붙여 사용.
    COMMENT_NO NUMBER PRIMARY KEY,
    WRITER_NO NUMBER NOT NULL,
    COMMENT_CONTENT VARCHAR2(400) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    FOREIGN KEY (WRITER_NO) REFERENCES USERS(USER_NO),
    CHECK(STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN COMMENTS.COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN COMMENTS.WRITER_NO IS '댓글번호';
COMMENT ON COLUMN COMMENTS.COMMENT_CONTENT IS '댓글번호';
COMMENT ON COLUMN COMMENTS.CREATE_DATE IS '댓글번호';
COMMENT ON COLUMN COMMENTS.STATUS IS '상태(미삭제:Y/삭제:N)';

CREATE SEQUENCE SEQ_COMMENTNO
NOCACHE;

INSERT INTO COMMENTS VALUES(SEQ_COMMENTNO.NEXTVAL, 3, '댓글 테스트 중입니다~~~', SYSDATE, DEFAULT);
INSERT INTO COMMENTS VALUES(SEQ_COMMENTNO.NEXTVAL, 1, '잘 되려나~~~', SYSDATE, DEFAULT);
INSERT INTO COMMENTS VALUES(SEQ_COMMENTNO.NEXTVAL, 2, '괜찮아 잘될거야', SYSDATE, DEFAULT);
INSERT INTO COMMENTS VALUES(SEQ_COMMENTNO.NEXTVAL, 5, '오호~~ 아무말대잔치', SYSDATE, DEFAULT);
INSERT INTO COMMENTS VALUES(SEQ_COMMENTNO.NEXTVAL, 4, '물결이 많다. 바다인가~~~', SYSDATE, DEFAULT);
INSERT INTO COMMENTS VALUES(SEQ_COMMENTNO.NEXTVAL, 1, '답글을 테스트하려면 댓글이 더 필요해요', SYSDATE, DEFAULT);
INSERT INTO COMMENTS VALUES(SEQ_COMMENTNO.NEXTVAL, 3, '그렇군요', SYSDATE, DEFAULT);

--------------------------------------------------------------------------------
--###############  댓글_답글  ###############
--------------------------------------------------------------------------------
CREATE TABLE COMMENT_REPLY(
    COM_REPLY_NO NUMBER PRIMARY KEY,
    ORIGIN_COM_NO NUMBER NOT NULL,
    REPLY_COM_NO NUMBER NOT NULL,
    FOREIGN KEY (ORIGIN_COM_NO) REFERENCES COMMENTS(COMMENT_NO),
    FOREIGN KEY (REPLY_COM_NO) REFERENCES COMMENTS(COMMENT_NO)
);

COMMENT ON COLUMN COMMENT_REPLY.COM_REPLY_NO IS '답글관리번호';
COMMENT ON COLUMN COMMENT_REPLY.ORIGIN_COM_NO IS '원본댓글번호';
COMMENT ON COLUMN COMMENT_REPLY.REPLY_COM_NO IS '답글댓글번호';

CREATE SEQUENCE SEQ_COMREPLYNO
NOCACHE;

INSERT INTO COMMENT_REPLY VALUES(SEQ_COMREPLYNO.NEXTVAL, 1, 2);
INSERT INTO COMMENT_REPLY VALUES(SEQ_COMREPLYNO.NEXTVAL, 2, 3);
INSERT INTO COMMENT_REPLY VALUES(SEQ_COMREPLYNO.NEXTVAL, 3, 4);
INSERT INTO COMMENT_REPLY VALUES(SEQ_COMREPLYNO.NEXTVAL, 4, 5);
INSERT INTO COMMENT_REPLY VALUES(SEQ_COMREPLYNO.NEXTVAL, 6, 7);

--------------------------------------------------------------------------------
--###############  알림  ############### (공통 헤더에 사용될 알림)
--------------------------------------------------------------------------------
CREATE TABLE NOTIFICATION(
    NOTI_NO NUMBER PRIMARY KEY,
    SENDER_NO NUMBER NOT NULL,
    RECEIVER_NO NUMBER NOT NULL,
    CONTENT VARCHAR2(255) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    READ CHAR(1) DEFAULT'N' NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    REFER_DB VARCHAR2(20),
    REFER_NO NUMBER,
    FOREIGN KEY (SENDER_NO) REFERENCES USERS(USER_NO),
    FOREIGN KEY (RECEIVER_NO) REFERENCES USERS(USER_NO),
    CHECK (READ IN ('Y', 'N')),
    CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN NOTIFICATION.NOTI_NO IS '알림번호';
COMMENT ON COLUMN NOTIFICATION.SENDER_NO IS '발신인번호';
COMMENT ON COLUMN NOTIFICATION.RECEIVER_NO IS '수신인번호';
COMMENT ON COLUMN NOTIFICATION.CONTENT IS '알림내용';
COMMENT ON COLUMN NOTIFICATION.CREATE_DATE IS '생성일';
COMMENT ON COLUMN NOTIFICATION.READ IS '읽기여부(읽음:Y/안읽음:N)';
COMMENT ON COLUMN NOTIFICATION.STATUS IS '상태(미삭제:Y/삭제:N)';
COMMENT ON COLUMN NOTIFICATION.REFER_DB IS '참조DB테이블명';
COMMENT ON COLUMN NOTIFICATION.REFER_NO IS '참조글번호';

CREATE SEQUENCE SEQ_NOTINO
NOCACHE;

INSERT INTO NOTIFICATION VALUES(SEQ_NOTINO.NEXTVAL, 3, 5, '주지훈(user02)님이 댓글을 남겼습니다.', SYSDATE, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO NOTIFICATION VALUES(SEQ_NOTINO.NEXTVAL, 1, 2, '나관리(admin)님이 설문조사를 요청하였습니다.', SYSDATE, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO NOTIFICATION VALUES(SEQ_NOTINO.NEXTVAL, 4, 2, '장원영(user03)님이 댓글을 남겼습니다.', SYSDATE, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO NOTIFICATION VALUES(SEQ_NOTINO.NEXTVAL, 5, 1, '손흥민(user04)님이 댓글을 남겼습니다.', SYSDATE, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO NOTIFICATION VALUES(SEQ_NOTINO.NEXTVAL, 2, 3, '차은우(user01)님이 댓글을 남겼습니다.', SYSDATE, DEFAULT, DEFAULT, NULL, NULL);

--------------------------------------------------------------------------------
--###############  주소록_카테고리  ###############
--------------------------------------------------------------------------------
CREATE TABLE CONTACTS_CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(50) NOT NULL UNIQUE 
);

COMMENT ON COLUMN CONTACTS_CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN CONTACTS_CATEGORY.CATEGORY_NAME IS '카테고리이름(ex) 세미프로젝트)';

CREATE SEQUENCE SEQ_CONTACTS_CATENO
NOCACHE;

INSERT INTO CONTACTS_CATEGORY VALUES(SEQ_CONTACTS_CATENO.NEXTVAL, '자바 미니 팀프로젝트');
INSERT INTO CONTACTS_CATEGORY VALUES(SEQ_CONTACTS_CATENO.NEXTVAL, '웹 클론 프로젝트');
INSERT INTO CONTACTS_CATEGORY VALUES(SEQ_CONTACTS_CATENO.NEXTVAL, '세미 프로젝트');
INSERT INTO CONTACTS_CATEGORY VALUES(SEQ_CONTACTS_CATENO.NEXTVAL, '파이널 프로젝트');
INSERT INTO CONTACTS_CATEGORY VALUES(SEQ_CONTACTS_CATENO.NEXTVAL, '자격증 스터디');

--------------------------------------------------------------------------------
--###############  주소록  ###############
--------------------------------------------------------------------------------
CREATE TABLE CONTACTS(
    CONTACTS_NO NUMBER PRIMARY KEY,
    CONTACTS_NAME VARCHAR2(50) NOT NULL,
    CONTACTS_TYPE CHAR(1) DEFAULT 'P' NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    CATEGORY_NO NUMBER,
    FOREIGN KEY (CATEGORY_NO) REFERENCES CONTACTS_CATEGORY(CATEGORY_NO),
    CHECK (CONTACTS_TYPE IN ('P', 'S')),
    CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON COLUMN CONTACTS.CONTACTS_NO IS '주소록번호';
COMMENT ON COLUMN CONTACTS.CONTACTS_NAME IS '주소록이름(ex) 세미프로젝트 2조)';
COMMENT ON COLUMN CONTACTS.CONTACTS_TYPE IS '주소록구분(개인:P/공유:S)';
COMMENT ON COLUMN CONTACTS.STATUS IS '상태(미삭제:Y/삭제:N)';
COMMENT ON COLUMN CONTACTS.CATEGORY_NO IS '카테고리번호';

CREATE SEQUENCE SEQ_CONTACTSNO
NOCACHE;

INSERT INTO CONTACTS VALUES(SEQ_CONTACTSNO.NEXTVAL, '세미프로젝트 1조', 'S', DEFAULT, 3);
INSERT INTO CONTACTS VALUES(SEQ_CONTACTSNO.NEXTVAL, '세미프로젝트 2조', 'S', DEFAULT, 3);
INSERT INTO CONTACTS VALUES(SEQ_CONTACTSNO.NEXTVAL, '세미프로젝트 3조', 'S', DEFAULT, 3);
INSERT INTO CONTACTS VALUES(SEQ_CONTACTSNO.NEXTVAL, '세미프로젝트 4조', 'S', DEFAULT, 3);
INSERT INTO CONTACTS VALUES(SEQ_CONTACTSNO.NEXTVAL, '세미프로젝트 5조', 'S', DEFAULT, 3);

--------------------------------------------------------------------------------
--###############  주소록_구성원  ###############
--------------------------------------------------------------------------------
CREATE TABLE CONTACTS_MEMBER(
    USER_NO NUMBER,
    CONTACTS_NO NUMBER,
    ROLE CHAR(1) CHECK (ROLE IN ('T', 'S', 'L', 'F')), 
    PRIMARY KEY (USER_NO, CONTACTS_NO),
    FOREIGN KEY (USER_NO) REFERENCES USERS(USER_NO),
    FOREIGN KEY (CONTACTS_NO) REFERENCES CONTACTS(CONTACTS_NO)
);

COMMENT ON COLUMN CONTACTS_MEMBER.USER_NO IS '유저번호';
COMMENT ON COLUMN CONTACTS_MEMBER.CONTACTS_NO IS '주소록번호';
COMMENT ON COLUMN CONTACTS_MEMBER.ROLE IS '역할';

INSERT INTO CONTACTS_MEMBER VALUES(1, 1, 'L');
INSERT INTO CONTACTS_MEMBER VALUES(2, 1, 'F');
INSERT INTO CONTACTS_MEMBER VALUES(3, 2, 'L');
INSERT INTO CONTACTS_MEMBER VALUES(4, 2, 'F');
INSERT INTO CONTACTS_MEMBER VALUES(5, 3, 'L');

--------------------------------------------------------------------------------
--###############  주소록_중요표시  ###############
--------------------------------------------------------------------------------
CREATE TABLE CONTACTS_STAR(
    STAR_NO NUMBER PRIMARY KEY,
    CURRENT_USER_NO NUMBER NOT NULL,
    OTHER_USER_NO NUMBER NOT NULL,
    STAR CHAR(1) DEFAULT 'Y' NOT NULL,
    FOREIGN KEY (CURRENT_USER_NO) REFERENCES USERS(USER_NO),
    FOREIGN KEY (OTHER_USER_NO) REFERENCES USERS(USER_NO),
    CHECK (STAR IN ('Y', 'N'))
);

COMMENT ON COLUMN CONTACTS_STAR.STAR_NO IS '중요표시번호';
COMMENT ON COLUMN CONTACTS_STAR.CURRENT_USER_NO IS '현유저번호';
COMMENT ON COLUMN CONTACTS_STAR.OTHER_USER_NO IS '타유저번호';
COMMENT ON COLUMN CONTACTS_STAR.STAR IS '중요표시(중요:Y/안중요:N)';

CREATE SEQUENCE SEQ_CONTACTS_STARNO
NOCACHE;

INSERT INTO CONTACTS_STAR VALUES(SEQ_CONTACTS_STARNO.NEXTVAL, 1, 2, DEFAULT);
INSERT INTO CONTACTS_STAR VALUES(SEQ_CONTACTS_STARNO.NEXTVAL, 1, 3, DEFAULT);
INSERT INTO CONTACTS_STAR VALUES(SEQ_CONTACTS_STARNO.NEXTVAL, 2, 1, DEFAULT);
INSERT INTO CONTACTS_STAR VALUES(SEQ_CONTACTS_STARNO.NEXTVAL, 2, 4, DEFAULT);
INSERT INTO CONTACTS_STAR VALUES(SEQ_CONTACTS_STARNO.NEXTVAL, 3, 5, DEFAULT);

--------------------------------------------------------------------------------
--###############  테이블명  ###############
--------------------------------------------------------------------------------


-- 커밋!!
COMMIT;